name: "build"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 16
          - 17
    name: Build ${{ matrix.node_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - name: Prepare
        run: npm install
      - name: Build
        run: npm test
